version: "3.8"
services:
  autossh:
    build: .
    container_name: autossh-tunnel
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      LOCAL_ADDR: "host.docker.internal"
      LOCAL_PORT: "8099"
      REMOTE_HOST: "remote-host-ip"
      REMOTE_ADDR: "0.0.0.0"
      REMOTE_PORT: "9100"
      SSH_USER: "username"
      FORWARD_TYPE: "R"
    volumes:
      - ./admin:/srv/ssh-key/id_rsa:ro
